IMG_TRAIN_DIR: data/train/images
MASK_TRAIN_DIR: data/train/masks
IMG_TEST_DIR: data/test/images
MASK_TEST_DIR: data/test/masks
CHECKPOINTS_DIR: checkpoints/checkpoint.pt
THR: 0.5

load_from_checkpoint: False
in_channels: 3
num_classes: 2
batch_size: 1
learning_rate: 0.0001
momentum: 0.99
num_epochs: 1000
